services:
  backend:
    build:
      context: ./bank-service
      dockerfile: Dockerfile
    container_name: container-app-java
    environment:
      DB_URL: jdbc:mysql://mysql:3306/dockertraefik
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql # nom du service
    restart: unless-stopped
    networks:
      - app-network


  mysql:
    image: mysql:8.0.40-debian
    container_name: container-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockertraefik
      MYSQL_USER: sidibe
      MYSQL_PASSWORD: passer123@
    ports:
      - "3306:3306"
    volumes: # montage du volume
      - mysql_data:/var/lib/mysql # repertoire d'installation de mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD # tester la santé du service
    networks:
      - app-network

  phpmyadmin:
    container_name: container-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: unless-stopped # redemarre juqua disponibilite de service mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# création du volume
volumes:
  mysql_data:
    driver: bridge # où se trouve le engine: docker va le gerer lui meme le driver c'est pour le volume
